version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: always
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  bc-backend:
    image: aelassas/bookcars-backend:latest
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/bookcars?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CDN_FOLDER: /var/www/cdn/bookcars
      BACKEND_PORT: 4002
    volumes:
      - cdn:/var/www/cdn/bookcars
      - backend_logs:/bookcars/backend/logs

  bc-admin:
    image: aelassas/bookcars-admin:latest
    restart: always
    depends_on:
      - bc-backend
    environment:
      REACT_APP_API_BASE_URL: ${API_BASE_URL}

  bc-frontend:
    image: aelassas/bookcars-frontend:latest
    restart: always
    depends_on:
      - bc-backend
    environment:
      API_BASE_URL: ${API_BASE_URL}
    volumes:
      - cdn:/var/www/cdn/bookcars

volumes:
  cdn:
  mongodb_data:
  mongodb_config:
  backend_logs:
