version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: bookcars-mongo
    restart: always
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27018:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: bookcars-mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "8084:8081"

  bc-backend:
    container_name: bookcars-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/bookcars?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CDN_FOLDER: /var/www/cdn/bookcars
      BACKEND_PORT: 4002
    ports:
      - "4002:4002"
    volumes:
      - cdn:/var/www/cdn/bookcars
      - backend_logs:/bookcars/backend/logs

  bc-admin:
    container_name: bookcars-admin
    build:
      context: .
      dockerfile: admin/Dockerfile
    depends_on:
      - bc-backend
    environment:
      REACT_APP_API_BASE_URL: ${API_BASE_URL}
    ports:
      - "3001:3001"

  bc-frontend:
    container_name: bookcars-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - bc-backend
    environment:
      API_BASE_URL: ${API_BASE_URL}
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - cdn:/var/www/cdn/bookcars

volumes:
  cdn:
  mongodb_data:
  mongodb_config:
  backend_logs:
